### PR TITLE
Enable `sample_flow_at_points` with heterogeneity

### PR DESCRIPTION
**Pull request by misi9170**
As pointed out by @fbelli997 in #1108 , `FlorisModel.sample_flow_at_points()` does not currently work if there is a heterogeneous map assigned to the `FlorisModel`. The underlying issue is that `FlowField.initialize_velocity_field()` does not work correctly when called with a `PointsGrid` and a `het_map`. This PR adds a bugfix to correctly size the necessary `x`, `y`, and `z` points arrays for the `PointsGrid` + `het_map` situation.

TODO:
- [x] implement fix
- [x] add appropriate tests

## Example runscript
The following script demonstrates the problem on develop and runs on this branch.
```python
from floris import FlorisModel


# Initialize FlorisModel
fmodel = FlorisModel("../inputs/gch.yaml")

# Change the layout to a 4 turbine layout in a box
fmodel.set(layout_x=[0, 0, 500.0, 500.0], layout_y=[0, 500.0, 0, 500.0])

# Set FLORIS to run for a single condition
fmodel.set(wind_speeds=[8.0], wind_directions=[270.0], turbulence_intensities=[0.06])

# Define the speed-ups of the heterogeneous inflow, and their locations.
# Note that heterogeneity is only applied within the bounds of the points defined in the
# heterogeneous_inflow_config dictionary.  In this case, set the inflow to be 1.25x the ambient
# wind speed for the upper turbines at y = 500m.
speed_ups = [[1.0, 1.25, 1.0, 1.25]]  # Note speed-ups has dimensions of n_findex X n_points
x_locs = [-500.0, -500.0, 1000.0, 1000.0]
y_locs = [-500.0, 1000.0, -500.0, 1000.0]

# Create the configuration dictionary to be used for the heterogeneous inflow.
heterogeneous_inflow_config = {
    "speed_multipliers": speed_ups,
    "x": x_locs,
    "y": y_locs,
}

# Set the heterogeneous inflow configuration (No error raised if this line is commented out)
fmodel.set(heterogeneous_inflow_config=heterogeneous_inflow_config)

# Run the FLORIS simulation
fmodel.run() # Works

fmodel.sample_flow_at_points([100], [100], [100]) # Does not work on develop
```

### CODE REVIEW

**Comment by misi9170** [comment]
I've now added tests to tests/heterogeneous_map_integration_test.py. These tests fail on the develop branch with the error described in #1108,
```
AttributeError: 'floris.core.grid.PointsGrid' object has no attribute 'x_sorted_inertial_frame'. Did you mean: 'y_sorted_inertial_frame'?
```
but pass on this bugfix branch.

Now ready for review.

**Review by paulf81 — APPROVED** [review]
Changes make sense.  I reviewed flow_field to convince myself that in the case that a PointsGrid is not passed in then the behavior is the same as before.  All tests pass on my computer.  Thanks @misi9170 !
